# -*- coding: utf-8 -*-
"""Ghaida_Nada_Nazihah.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WA7vQzawCZ2xM4XZ8V0H55iMY-F5mAiU
"""

print('Ghaida Nada Nada')

